DMS/DMS.UI/Controllers/Main/RolePermissionController.cs
using AutoMapper;
using DMS.DAL.DatabaseContext;
using DMS.DAL.EntityModels;
using DMS.DAL.Helpers;
using DMS.Services.General.Interface;
using DMS.UI.Services.General.Interface;
using DMS.UI.ViewModels;
using DMS.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DMS.Controllers
{
    [CustomAuthentication]
    public class RolePermissionController : Controller
    {
        //private IEmployeeServices _employee;
        private IMenuServices _menuServices;
        private IRolePermissionServices _rolepermission;
        private IUserRoleServices _userRole;
        protected readonly IdentityEntities _db = new IdentityEntities();



        public RolePermissionController(IMenuServices menuServices, IRolePermissionServices rolepermission, IUserRoleServices UserRole)
        {
            //_employee = employee;
            _menuServices = menuServices;
            _rolepermission = rolepermission;
            _userRole = UserRole;
            //_DocHandlerService = DocHandlerService;
        }
        // GET: RolePermission

        [HttpGet]
        public ActionResult Index()
        {
            var roleStore = new RoleStore<IdentityRole>(_db);
            var roleMngr = new RoleManager<IdentityRole>(roleStore);

            var roles = roleMngr.Roles.ToList();
            return View(roles);
        }

        [HttpGet]
        public async Task<ActionResult> SetPermission(string Emp_Type)
        {
            Role_Permission_VM Role_Permission_VM = new Role_Permission_VM();
            Role_Permission_VM.ApplicationRole = await _userRole.GetById(Emp_Type);
            if (Role_Permission_VM.ApplicationRole == null)
            {
                throw new Exception("User Role Id Not Found");
            }

            //_employee.GetEmployeeTypeList().Where(x => x.Emp_Type == Emp_Type).FirstOrDefault();
            List<AspNetRoleMenuItem> AlredySelectedMenuItems = _rolepermission.GetApplicationUserMenuList().Where(x => x.RoleId == Emp_Type).ToList();

            List<MenuListVM> AllMenuItems = Mapper.Map<List<MenuListVM>>(await _menuServices.GetAll());
            List<MenuListVM> SelectedMenuListVMList = AllMenuItems.Where(x => AlredySelectedMenuItems.Any(y => y.MenuListId == x.Id)).ToList();
            List<MenuListVM> NotSelectedMenuListVMList = AllMenuItems.Where(x => !SelectedMenuListVMList.Any(y => y.Id == x.Id)).ToList();
            Role_Permission_VM.SelectedMenuListVMList = SelectedMenuListVMList;
            Role_Permission_VM.NotSelectedMenuListVMList = NotSelectedMenuListVMList;
            return View(Role_Permission_VM);
        }

        [HttpPost]
        public ActionResult SetPermission(string Emp_Type, int[] Perm1)
        {
            try
            {
                _rolepermission.CreateMenuListbyEmpType(Emp_Type, Perm1);
                TempData["Message"] = "Permission has been given Successfully.";

            }
            catch (Exception ex)
            {

                throw ex;
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> UserList(string id)
        {
            //check conversion
            ApplicationRoleVM List = _userRole.GetUserListWithRole(id);
            //EnumEmployeeRoles uData = EnumEmployeeRoles.LoanInitiator;
            //Enum.TryParse(id, out uData);
            //ViewBag.EmpType = uData.ToString();
            //IEnumerable<VMDocHanlderDetails> List1 = await _DocHandlerService.GetListByRole(uData);
            return View(List);
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(string RoleName)
        {
            try
            {
                if (RoleName.Trim().Length <= 0)
                {
                    throw new Exception("Role Name Required.");
                }
                _userRole.AddRole(RoleName);
                FlashBag.setMessage(true, "New Role Created Successfully. " + RoleName);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ErrorHelper.GetMsg(ex));
            }
            return View();
        }
    }
}

DMS/DMS.UI/Views/RolePermission/Create.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="toolbar row">
        <div class="col-sm-6 hidden-xs">
            <div class="page-header">
                <h1 class="upper">Role<small>List</small> </h1>
            </div>
        </div>
        <div class="col-sm-6 col-xs-12">
            <div class="toolbar-tools pull-right">
                <!-- start: TOP NAVIGATION MENU -->
                <ul class="nav navbar-right">
                    <!-- start: TO-DO DROPDOWN -->
                    <li class="back">
                        <a href="@Url.Action("Index")">
                            <i class="fa fa-chevron-left"></i> BACK
                        </a>
                    </li>
                </ul>
                <!-- end: TOP NAVIGATION MENU -->
            </div>
        </div>
    </div>
    @Html.Raw(FlashBag.showMessage())
    <div class="row">
        <div class="col-md-12">
            <!-- start: FORM VALIDATION 1 PANEL -->
            <div class="panel panel-white">


                <div class="panel-body">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            <div class="row form-group">
                                <div class="col-sm-3">Role Name</div>
                                <div class="col-sm-3">
                                    <input type="text" name="RoleName" value="" class="form-control" />
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-sm-3">&nbsp;</div>
                                <div class="col-sm-3">
                                    <button class="btn btn-success" type="submit">
                                        <i class="fa fa-check"></i>
                                        Save
                                    </button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

DMS/DMS.UI/Views/RolePermission/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="toolbar row">
        <div class="col-sm-6 hidden-xs">
            <div class="page-header">
                <h1 class="upper">Role Permission<small>List</small> </h1>
            </div>
        </div>
        <div class="col-sm-6 col-xs-12">
            <a href="#" class="back-subviews">
                <i class="fa fa-chevron-left"></i> BACK
            </a>
            <a href="#" class="close-subviews">
                <i class="fa fa-times"></i> CLOSE
            </a>
            <div class="toolbar-tools pull-right">
                <!-- start: TOP NAVIGATION MENU -->
                <ul class="nav navbar-right">
                    <!-- start: TO-DO DROPDOWN -->
                    <li>
                        <a href="@Url.Action("Create")">
                            <i class="fa fa-plus"></i> Add new
                        </a>
                    </li>
                    <li>
                        <a href="#" class="cmdPrint">
                            <i class="fa fa-print"></i> Print
                        </a>
                    </li>
                    <li class="back">
                        <a href="@Url.Action("DashBoard","Home")">
                            <i class="fa fa-chevron-left"></i> Back
                        </a>
                    </li>
                </ul>
                <!-- end: TOP NAVIGATION MENU -->
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <!-- start: FORM VALIDATION 1 PANEL -->
            <div class="panel panel-white">


                <div class="panel-body">

                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-bordered dataTable">
                            <thead>
                                <tr>
                                    <th colspan="2">
                                        Roles
                                    </th>
                            </thead>
                            <tbody>
                                @foreach (var role in Model)
                                {
                                    <tr>
                                        <td>
                                            <strong>@role.Name  </strong>
                                        </td>
                                        <td><a class="btn-sm btn-green tooltips" href="@Url.Action("SetPermission", new { Emp_Type = role.Id})">Permission</a>|<a class="btn-sm btn-green tooltips" href="@Url.Action("UserList","RolePermission", new { id = role.Id})">User List</a></td>

                                    </tr>
                                }
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DMS/DMS.UI/Views/RolePermission/SetPermission.cshtml
@model DMS.ViewModels.Role_Permission_VM


@{ ViewBag.Title = "Set Permission";
    var SelectedMenuList = Model.SelectedMenuListVMList;
    var UnSelectedMenuList = Model.NotSelectedMenuListVMList;
}
<div class="">
    <!-- start: PAGE HEADER -->
    <!-- start: TOOLBAR -->
    <!---->
    <div class="toolbar row">
        <div class="col-sm-6 hidden-xs">
            <div class="page-header">
                <h1 class="uc">Menu List</h1>

            </div>
        </div>
        <div class="col-sm-6 col-xs-12">
            <div class="toolbar-tools pull-right">
                <!-- start: TOP NAVIGATION MENU -->
                <ul class="nav navbar-right">
                    <li class="back">
                        <a id="SubmitButton">
                            <i class="fa fa-check"></i> Save
                        </a>

                    </li>
                    <li class="back">
                        <a href="@Url.Action("Index","RolePermission")">
                            <i class="fa fa-chevron-left"></i> Back
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- end: TOOLBAR -->
    <!-- end: PAGE HEADER -->
    <!-- start: PAGE CONTENT -->
    <div class="row">
        <div class="col-xs-12">
            <!-- start: FORM VALIDATION 1 PANEL -->
            <form action="" method="post" class="form-horizontal">
                <div class="panel panel-default">
                    <!--wrapper-->
                    <!--extra-->
                    <div class="panel panel-heading"> <h4>Employee Type : @Html.DisplayFor(x => x.ApplicationRole.Name)</h4></div>
                    <div class="panel-body">
                        <!--Body-->
                        <!--BODY STARTS-->
                        @if (TempData["Message"] != null)
                        {
                            <div class="alert alert-info">@TempData["Message"]</div>
                        }
                        <input type="hidden" name="Emp_Type" value="@Model.ApplicationRole.Id" />
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>ID</th>
                                    <th>
                                        @Html.DisplayName("Title")
                                    </th>
                                    <th>
                                        @Html.DisplayName("ControllerName")
                                    </th>
                                    <th>
                                        @Html.DisplayName("ActionName")
                                    </th>
                                    <th>
                                        @Html.DisplayName("Description")
                                    </th>
                                    <th>
                                        @Html.DisplayName("IconName")
                                    </th>
                                    <th>
                                        @Html.DisplayName("Position")
                                    </th>
                                    <th>
                                        @Html.DisplayName("IsActive")
                                    </th>
                                </tr>
                            </thead>

                            <tbody>
                                @if (SelectedMenuList.Any())
                                {
                                    foreach (var item in SelectedMenuList)
                                    {

                                        <tr>
                                            <td>
                                                <input type="checkbox" name="Perm1[]" value="@item.Id" checked />
                                            </td>
                                            <td>@item.Id</td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Title)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ControllerAction.ControllerName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ControllerAction.ActionName)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.Description)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.IconName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Position)
                                            </td>
                                            <td>
                                                <div type="button" class="btn btn-info btn-sm">
                                                    @if (item.IsActive)
                                                    {
                                                        <lable>Active</lable>

                                                    }
                                                    else
                                                    {
                                                        <lable>DeActive</lable>
                                                    }
                                                </div>
                                            </td>

                                        </tr>
                                    }
                                }
                                @if (UnSelectedMenuList.Any())
                                {
                                    foreach (var item in UnSelectedMenuList)
                                    {

                                        <tr>
                                            <td>
                                                <input type="checkbox" name="Perm1[]" value="@item.Id" />
                                            </td>
                                            <td>@item.Id</td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Title)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ControllerAction.ControllerName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ControllerAction.ActionName)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.Description)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.IconName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Position)
                                            </td>
                                            <td>
                                                <div type="button" class="btn btn-info btn-sm">
                                                    @if (item.IsActive)
                                                    {
                                                        <lable>Active</lable>

                                                    }
                                                    else
                                                    {
                                                        <lable>DeActive</lable>
                                                    }
                                                </div>
                                            </td>

                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                        <!--BODY ENDS-->
                        <div class="row">
                            <div class="col-md-offset-5 col-md-3">
                                <div class="col-sm-6 ">
                                    <button id="SubmitButton" type="button" class="btn btn-block btn-success"> <i class="fa fa-check"></i> Save</button>
                                </div>


                            </div>
                        </div>
                        <!--End Body-->
                    </div>
                    <!--wrapper row ends-->
                </div>
                <div class="container">
                    <!-- Modal -->
                    <div class="modal fade" id="myModal" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header" style="background-color:#ce181f">
                                    <button type="button" class="close" style="padding:5px; border-radius:30px 30px;" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title" style="color:white">Are you Sure!</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="row">
                                        <p>Do you want to <span id="msg">Submit</span>?</p>
                                    </div>

                                </div>
                                <div class="modal-footer">
                                    <button type="submit" value="Yes" id="ModalSubmitButton" class="btn btn-primary fa fa-check" style="margin:0 30px 0px 0px">Yes</button>
                                    <button type="button" value="No" id="No" class="btn btn-danger fa fa-remove" data-dismiss="modal">No</button>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

DMS/DMS.UI/Views/RolePermission/UserList.cshtml
@model DMS.UI.ViewModels.ApplicationRoleVM


@{
    ViewBag.Title = "Set Permission";
}
<div class="">
    <!-- start: PAGE HEADER -->
    <!-- start: TOOLBAR -->
    <!---->
    <div class="toolbar row">
        <div class="col-sm-6 hidden-xs">
            <div class="page-header">
                <h1 class="uc">
                    Role User List
                    <small>Employee Type : @(ViewBag.EmpType)</small>
                </h1>
            </div>
        </div>
        <div class="col-sm-6 col-xs-12">
            <div class="toolbar-tools pull-right">
                <!-- start: TOP NAVIGATION MENU -->
                <ul class="nav navbar-right">
                    <li class="back">
                        <a href="@Url.Action("Index","RolePermission")">
                            <i class="fa fa-chevron-left"></i> Back
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- end: TOOLBAR -->
    <!-- end: PAGE HEADER -->
    <!-- start: PAGE CONTENT -->
    <div class="row">
        <div class="col-xs-12">
            <!-- start: FORM VALIDATION 1 PANEL -->
            <form action="" method="post" class="form-horizontal">
                <div class="panel-body">
                    <div class="row">
                        <!--wrapper-->
                        <!--extra-->
                        <div class="panel panel-primary">
                            <div class="panel panel-body">
                                <!--Body-->

                                <div class="col-md-12">


                                    <!--BODY STARTS-->
                                    <table class="table dataTable table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th>ID</th>
                                                <th>
                                                    Name
                                                </th>
                                                <th>
                                                    Email
                                                </th>
                                                <th>
                                                   Role
                                                </th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            @if (Model != null)
                                            {
                                            if (Model.applicationUserVm != null)
                                            {
                                                foreach (var item in Model.applicationUserVm)
                                                {
                                            <tr>
                                                <td></td>
                                                <td>@item.Id</td>
                                                @*<td>
                                                    @if (item.IsGroup)
                                                    {
                                                    <a href="@Url.Action("Details", "EmployeeGroup", new { id = item.GroupID })">@item.Name</a>
                                                    }
                                                    else
                                                    {
                                                    @Html.DisplayFor(modelItem => item.Name)
                                                    }
                                                </td>*@
                                                <td>
                                                  @item.UserName
                                                </td>
                                                <td>
                                                  @item.Email
                                                </td>
                                                <td>@item.IsAssignRole</td>
                                            </tr>
                                                }
                                            }
                                            }
                                        </tbody>
                                    </table>
                                    <!--BODY ENDS-->

                                </div>
                                <!--End Body-->
                            </div>
                        </div>
                        <!--wrapper row ends-->
                    </div>
                </div>
                <div class="container">
                    <!-- Modal -->
                    <div class="modal fade" id="myModal" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header" style="background-color:#ce181f">
                                    <button type="button" class="close" style="padding:5px; border-radius:30px 30px;" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title" style="color:white">Are you Sure!</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="row">
                                        <p>Do you want to <span id="msg">Submit</span>?</p>
                                    </div>

                                </div>
                                <div class="modal-footer">
                                    <button type="submit" value="Yes" id="ModalSubmitButton" class="btn btn-primary fa fa-check" style="margin:0 30px 0px 0px">Yes</button>
                                    <button type="button" value="No" id="No" class="btn btn-danger fa fa-remove" data-dismiss="modal">No</button>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>